<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: kyc.proto

namespace Kyc\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;
use User\Services\Grpc;

interface KycServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "Kyc.services.grpc.KycService";

    /**
    * @param Context $context
    * @param Grpc\User $request
    * @return Acknowledge
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function checkKYCStatus(Context $context, Grpc\User $request): Acknowledge;
}
