<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlm.proto

namespace MLM\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MLM.services.grpc.UserDescendantCheck</code>
 */
class UserDescendantCheck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_index_id = 1;</code>
     */
    protected $user_index_id = 0;
    /**
     * Generated from protobuf field <code>int64 user_to_show_id = 2;</code>
     */
    protected $user_to_show_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_index_id
     *     @type int|string $user_to_show_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mlm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_index_id = 1;</code>
     * @return int|string
     */
    public function getUserIndexId()
    {
        return $this->user_index_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_index_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserIndexId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_index_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_to_show_id = 2;</code>
     * @return int|string
     */
    public function getUserToShowId()
    {
        return $this->user_to_show_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_to_show_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserToShowId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_to_show_id = $var;

        return $this;
    }

}

