<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.services.grpc.UserTransactionPassword</code>
 */
class UserTransactionPassword extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transaction_password = 1;</code>
     */
    protected $transaction_password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transaction_password = 1;</code>
     * @return string
     */
    public function getTransactionPassword()
    {
        return $this->transaction_password;
    }

    /**
     * Generated from protobuf field <code>string transaction_password = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_password = $var;

        return $this;
    }

}

