<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\Services\Grpc;

use UnexpectedValueException;

/**
 * Protobuf type <code>user.services.grpc.WalletType</code>
 */
class WalletType
{
    /**
     * Generated from protobuf enum <code>USDT = 0;</code>
     */
    const USDT = 0;

    private static $valueToName = [
        self::USDT => 'USDT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

